   ;; (use-package general
   ;;   :ensure t
   ;;   :after evil
   ;;   :config
   ;;   (general-evil-setup t)
   ;;   (general-override-mode 1)
   ;;   (general-create-definer gmap
   ;; 	:keymaps 'override
   ;; 	:states '(motion normal visual)
   ;; 	:prefix "SPC")
   ;;   (general-create-definer lmap
   ;; 	:keymaps 'override
   ;; 	:states '(motion normal visual)
   ;; 	:prefix ","))

;; (mmap                                           ; Motion map
;;   "^" 'dired-jump)
;; (vmap                                           ; Visual map
;;   "ii" 'er/expand-region)
;; (gmap                                           ; Space menu
;;   "SPC" '(execute-extended-command :which-key "cmd")
;;   "TAB" '(tab-bar-echo-area-display-tab-names :wk "tabs")
;;   "1" '(tab-bar-select-tab :which-key "1")
;;   "2" '(tab-bar-select-tab :which-key "2")
;;   "3" '(tab-bar-select-tab :which-key "3")
;;   "4" '(tab-bar-select-tab :which-key "4")
;;   "5" '(tab-bar-select-tab :which-key "5")
;;   "6" '(tab-bar-select-tab :which-key "6")
;;   "7" '(tab-bar-select-tab :which-key "7")
;;   "8" '(tab-bar-select-tab :which-key "8")
;;   "9" '(tab-bar-select-tab :which-key "9")
;;   "a" '(org-agenda :which-key "agenda")
;;   "b" '(consult-buffer :which-key "buffer")
;;   "d" '(dired-jump :which-key "dired")
;;   "f" '(find-file :which-key "file")
;;   "g" '(magit :which-key "git")
;;   "h" `(,help-map :which-key "help")
;;   "i" '(imenu :which-key "imenu")
;;   "j" '(bookmark-jump :which-key "jump")
;;   "k" '(kill-this-buffer :which-key "kill")
;;   "n" `(,narrow-map :which-key "narrow")
;;   "o" '(ace-window :which-key "other")
;;   "p" `(,project-prefix-map :which-key "project")
;;   "q" '(delete-window :which-key "quit window")
;;   "Q" '(tab-close :which-key "quit tab")
;;   "r" '(recentf :which-key "recent")
;;   "s" '(save-buffer :which-key "save")
;;   "t" '(tab-bar-new-tab :which-key "tab")
;;   "w" `(,evil-window-map :which-key "window")
;;   "y" '(clone-indirect-buffer-other-window :which-key "indirect"))
;; (lmap                                           ; Major modes
;;   "," (general-key "C-c C-c")
;;   "a" (general-key "C-c C-a")
;;   "b" (general-key "C-c C-b")
;;   "c" (general-key "C-c C-c")
;;   "d" (general-key "C-c C-d")
;;   "e" (general-key "C-c C-e")
;;   "f" (general-key "C-c C-f")
;;   "g" (general-key "C-c C-g")
;;   "h" (general-key "C-c C-h")
;;   "i" (general-key "C-c C-i")
;;   "j" (general-key "C-c C-j")
;;   "k" (general-key "C-c C-k")
;;   "l" (general-key "C-c C-l")
;;   "m" (general-key "C-c C-m")
;;   "n" (general-key "C-c C-n")
;;   "o" (general-key "C-c C-o")
;;   "p" (general-key "C-c C-p")
;;   "q" (general-key "C-c C-q")
;;   "r" (general-key "C-c C-r")
;;   "s" (general-key "C-c C-s")
;;   "t" (general-key "C-c C-t")
;;   "u" (general-key "C-c C-u")
;;   "v" (general-key "C-c C-v")
;;   "w" (general-key "C-c C-w")
;;   "x" (general-key "C-c C-x")
;;   "y" (general-key "C-c C-y")
;;   "z" (general-key "C-c C-z"))
;; (lmap                                           ; Minor modes
;;   "!"  (general-key "C-c !" )
;;   "\"" (general-key "C-c \"")
;;   "#"  (general-key "C-c #" )
;;   "$"  (general-key "C-c $" )
;;   "%"  (general-key "C-c %" )
;;   "&"  (general-key "C-c &" )
;;   "'"  (general-key "C-c '" )
;;   "("  (general-key "C-c (" )
;;   ")"  (general-key "C-c )" )
;;   "*"  (general-key "C-c *" )
;;   "+"  (general-key "C-c +" )
;;   "-"  (general-key "C-c -" )
;;   "."  (general-key "C-c ." )
;;   "/"  (general-key "C-c /" )
;;   ":"  (general-key "C-c :" )
;;   ";"  (general-key "C-c ;" )
;;   "<"  (general-key "C-c <" )
;;   "="  (general-key "C-c =" )
;;   ">"  (general-key "C-c >" )
;;   "?"  (general-key "C-c ?" )
;;   "@"  (general-key "C-c @" )
;;   "["  (general-key "C-c [" )
;;   "\\" (general-key "C-c \\")
;;   "]"  (general-key "C-c ]" )
;;   "^"  (general-key "C-c ^" )
;;   "_"  (general-key "C-c _" )
;;   "`"  (general-key "C-c `" )
;;   "{"  (general-key "C-c {" )
;;   "|"  (general-key "C-c |" )
;;   "}"  (general-key "C-c }" )
;;   "~"  (general-key "C-c ~" ))
