# Homebrew package list. These are intended to be installed on *all* my
# machines, so I only list the packages that I *really* need everywhere.
# Packages I only need on some computers are instead installed manually.

tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"

brew "atool"
brew "bat"
brew "cloc"
brew "direnv"
brew "entr"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "htop"
brew "hugo"
brew "iconsur"
brew "latexdiff"
brew "latexindent"
brew "lzip"
brew "moreutils"
brew "neovim"
brew "openconnect"
brew "pandoc"
brew "rg"
brew "tectonic"
brew "tmux"
brew "wget"
brew "zoxide"
brew "zsh"

cask "alfred"
cask "arq"
cask "firefox"
cask "iterm2"
cask "macvim"
cask "miniconda"
cask "quarto"
cask "rectangle"
cask "skim"
cask "visual-studio-code"
cask "vlc"
cask "yt-music"
cask "zoom"
cask "zotero"

cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-jetbrains-mono"
cask "font-juliamono"
cask "font-libertinus"
