# ~/.config/Brewfile: HomeBrew packages and repositories.

tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-fonts"

brew "atool"
brew "bat"
brew "cloc"
brew "direnv"
brew "entr"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "htop"
brew "hugo"
brew "latexdiff"
brew "latexindent"
brew "lzip"
brew "moreutils"
brew "openconnect"
brew "pandoc"
brew "rg"
brew "tectonic"
brew "tmux"
brew "wget"
brew "zsh"

cask "airflow"
cask "alfred"
cask "arq"
cask "espanso"
cask "firefox"
cask "iterm2"
cask "julia"
cask "karabiner-elements"
cask "logseq"
cask "macvim"
cask "miniconda"
cask "quarto"
cask "skim"
cask "swish"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "yt-music"
cask "zoom"
cask "zotero"

cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-gnu-unifont"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-juliamono"
cask "font-libertinus"
