# ~/.config/starship.toml

[git_branch]
disabled = true

[git_status]
prefix = '('
suffix = ') '
ahead = 'p'
behind = 'p'
diverged = 'p'
conflicted = '!'
untracked = '?'
modified = 'm'
deleted = 'd'
staged = 's'
renamed = 'r'
stashed = ''

[python]
symbol = 'python '

[conda]
symbol = 'conda '

[package]
symbol = ''
