;;; kkp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kkp.el

(autoload 'kkp-disable-in-terminal "kkp" "\
Disable in this terminal where command is executed, the activated enhancements." t)
(defvar global-kkp-mode nil "\
Non-nil if Global Kkp mode is enabled.
See the `global-kkp-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-kkp-mode'.")
(custom-autoload 'global-kkp-mode "kkp" nil)
(autoload 'global-kkp-mode "kkp" "\
Toggle KKP support in all terminal frames.

This is a global minor mode.  If called interactively, toggle the
`Global Kkp mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='global-kkp-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'kkp-status "kkp" "\
Message, if terminal supports KKP, if yes, currently enabled enhancements." t)
(register-definition-prefixes "kkp" '("kkp-"))

;;; End of scraped data

(provide 'kkp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kkp-autoloads.el ends here
