[[language]]
name = "python"
file-types = ["py"]
roots = ["pyproject.toml", "pyrightconfig.json"]

# Pyright language server.
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = { "analysis" = { "autoSearchPaths" = true, "diagnosticMode" = "workspace", "useLibraryCodeForTypes" = true } }

# Black autoformatter.
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
