" vim: fdm=marker shiftwidth=2

" Built-in: Settings {{{
  set mouse=a

  set noshowcmd
  set noshowmode
  set signcolumn=no

  set shortmess+=I
  set fillchars+=eob:\ ,

  set nowrap
  set linebreak
  set breakindent

  set smarttab
  set expandtab
  set shiftwidth=4

  set splitright
  set splitbelow
" }}}

" Built-in: Packages {{{
  runtime macros/matchit.vim
  runtime ftplugin/man.vim
" }}}

" Plugin: Installation {{{
  call plug#begin('~/.cache/vim/plug.vim')

  " Keybindings
  Plug 'tpope/vim-rsi'
  Plug 'tpope/vim-commentary'
  Plug 'rhysd/clever-f.vim'
  " visualstar

  " Text objects
  Plug 'machakann/vim-sandwich'
  Plug 'wellle/targets.vim'
  Plug 'michaeljsmith/vim-indent-object'
  Plug 'kana/vim-textobj-user'
  Plug 'kana/vim-textobj-entire'

  " IDE features
  Plug 'dense-analysis/ale'
  Plug 'junegunn/fzf'
  Plug 'junegunn/fzf.vim'

  " Language support
  Plug 'kalekundert/vim-coiled-snake'
  Plug 'lervag/vimtex'

  " Nice looks
  Plug 'jeffkreeftmeijer/vim-dim'
  Plug 'jrudess/vim-foldtext'
  Plug 'vim/colorschemes'
  Plug 'dracula/vim'

  " Miscellaneous
  Plug 'sunaku/tmux-navigate'

  call plug#end()
" }}}

" Plugin: ALE {{{
  " Show docstrings as pop-ups.
  let g:ale_floating_preview = 1
  let g:ale_floating_window_border = ['│', '─', '┌', '┐', '┘', '└', '│', '─']
" }}}

" Config: Keybindings {{{
  " Ergonomic folding.
  nnoremap <tab> za
  nnoremap <S-tab> zM
" }}}

" Config: Aesthetics {{{
  " Base colorscheme.
  set termguicolors
  colorscheme dracula

  " Avoid excessive highlighting.
  highlight! link Folded Comment

  " Don't show fold text.
  let g:FoldText_info=0
" }}}
