" ~/.vim/vimrc: Vim configuration file.
" NOTE: Moving to ~/.config/vim/vimrc in Vim 9.1.x.
vim9script
source $VIMRUNTIME/defaults.vim

# Built-in packages {{{
  packadd! matchit
# packadd! comment
# }}} 

# Settings {{{
  nnoremap <space> <nop>
  g:mapleader = " "
  g:maplocalleader = ","

  set termguicolors
  set clipboard=unnamed
  set encoding=utf-8
  set mouse=a
  set smoothscroll
  set display=lastline
  set hidden

  set noshowcmd
  set noshowmode
  set noruler
  set number
  set signcolumn=number

  set nowrap
  set linebreak
  set breakindent
  set nofoldenable
  set conceallevel=0
  set breakindentopt=list:-1

  set smartcase
  set ignorecase

  set smarttab
  set expandtab
  set shiftwidth=4
  set tabstop=4

  set splitright
  set splitbelow

  set shortmess+=I
  set fillchars+=eob:\ ,
      set virtualedit=block
  set wildoptions=pum
  set tildeop

  set spelllang=en_US,nb_NO
# }}}

# Package config {{{
  g:ale_floating_preview = 1
  g:ale_floating_window_border = ['│', '─', '┌', '┐', '┘', '└', '│', '─']
  g:ale_virtualtext_cursor = 0

  g:pandoc#syntax#conceal#blacklist = [
    'subscript',
    'superscript',
    'atx',
    'codeblock_start',
    'codeblock_delim',
    'list',
    'quotes',
    'inlinecode',
  ]

  g:FoldText_info = 0

  g:netrw_banner = 0

  g:UltiSnipsExpandTrigger = "<tab>"
  g:UltiSnipsJumpForwardTrigger = "<tab>"
  g:UltiSnipsJumpBackwardTrigger = "<S-tab>"

  g:vimtex_imaps_leader = ";"
  g:vimtex_mappings_prefix = "<localleader>"

  g:wiki_root = '/Users/jabirali/iCloud/Notes'
  g:wiki_zotero_root = '/Users/jabirali/Zotero'
  g:wiki_filetypes = ['md']
  g:wiki_link_extension = '.md'
  g:wiki_mappings_local_journal = 
  \ {
  \  '<plug>(wiki-journal-prev)': '[f',
  \  '<plug>(wiki-journal-next)': ']f',
  \ }
  g:wiki_journal = 
  \ {
  \   'root': '',
  \   'name': 'journal',
  \   'frequency': 'daily',
  \   'date_format': {
  \     'daily': '%Y-%m-%d',
  \     'weekly': '%Y-W%W',
  \   },
  \ }
# }}}

# Package management {{{
  plug#begin('~/.cache/vim/plug.vim')
  Plug 'rose-pine/vim'

  # Keybindings
  Plug 'tpope/vim-rsi'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-unimpaired'
  Plug 'tpope/vim-speeddating'
  Plug 'tpope/vim-repeat'
  Plug 'kana/vim-textobj-user'
  Plug 'kana/vim-textobj-entire'
  Plug 'kana/vim-textobj-line'
  Plug 'kana/vim-textobj-indent'
  Plug 'kana/vim-textobj-syntax'
  Plug 'wellle/targets.vim'
  Plug 'rhysd/clever-f.vim'
  Plug 'bronson/vim-visual-star-search'

  # IDE features
  Plug 'dense-analysis/ale'
  Plug 'junegunn/fzf'
  Plug 'junegunn/fzf.vim'
  Plug 'sirver/ultisnips'

  # Language support
  Plug 'kalekundert/vim-coiled-snake'
  Plug 'vim-pandoc/vim-pandoc'
  Plug 'vim-pandoc/vim-pandoc-syntax'
  Plug 'lervag/vimtex'

  # Aesthetics
  Plug 'jeffkreeftmeijer/vim-dim'
  Plug 'jrudess/vim-foldtext'
  Plug 'vim/colorschemes'
  Plug 'dracula/vim'

  # Miscellaneous
  # Plug 'lervag/wiki.vim'
  Plug 'vimwiki/vimwiki'
  # Plug 'tools-life/taskwiki'
  Plug 'sunaku/tmux-navigate'

  plug#end()
# }}}

# Keybindings {{{
  # Tabs
  nnoremap <space>1 1gt
  nnoremap <space>2 2gt
  nnoremap <space>3 3gt
  nnoremap <space>4 4gt
  nnoremap <space>5 5gt
  nnoremap <space>6 6gt
  nnoremap <space>7 7gt
  nnoremap <space>8 8gt
  nnoremap <space>9 9gt

  nnoremap <space>q <cmd>quit<cr>
  nnoremap <space>w <cmd>close<cr>
  nnoremap <space>t <cmd>tabnew<cr>
  nnoremap <space>s <cmd>write<cr>

  # Fuzzy finder
  nnoremap <space>b  :Buffers<cr>
  nnoremap <space>f  :Files<cr>
  # nnoremap <space>s  :Snippets<cr>
  nnoremap <space>h  :Helptags<cr>
  nnoremap <space>'  :Marks<cr>
  nnoremap <space>/  :RG<cr>

  # Package management
  nnoremap <space>e :edit ~/.vim/<cr>
  nnoremap <space>p :source<bar>PlugInstall<cr>

  # Personal wiki (todo/note/journal)
  #nnoremap <space>t :WikiIndex<cr>
  #nnoremap <space>n :WikiPages<cr>
  #nnoremap <space>j :WikiJournal<cr>

  # Surround
  nmap s ys
  vmap s S

  # Digraphs
  # inoremap ;   <c-k>
  # inoremap ;;  <c-k>*

  # inoremap ;<space> ;<space>
  # inoremap ;<cr>    ;<cr>
# }}}

# Digraphs {{{
# Norwegian
#  digraphs Ae 198 " Æ
#  digraphs Oo 216 " Ø
#  digraphs Aa 197 " Å
#  digraphs ae 230 " æ
#  digraphs oo 248 " ø
#  digraphs aa 229 " å
#
#  # Math
#  digraphs *A 8704  " ∀
#  digraphs *E 8707  " ∃
#  digraphs *I 8747  " ∫
#  digraphs *S 8721  " ∑
#  digraphs *V 8711  " ∇
#  digraphs *s  963  " σ
#  digraphs *v 8706  " ∂
#  digraphs *.  183  " ·
#  digraphs *= 8801  " ≡ 
#  digraphs *~ 8776  " ≈
  # }}}

# Colorscheme {{{
  colorscheme rosepine_moon
  highlight! link Folded LineNr
# }}}

# vim: fdm=marker shiftwidth=2
