# ~/.config/kak/kakrc

# Quickstart:
# - Clone `andreyorst/plug.kak` into ~/.config/kak/plugins/plug.kak;
# - Run `:plug-install` to install all the plugins listed below;
# - Start `kak` in `tmux` to integrate `fzf`, `repl`, etc.

# External modules.
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "andreyorst/fzf.kak"
plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
}

# Settings.
colorscheme solarized-dark-termcolors
set global ui_options ncurses_assistant=none
lsp-enable

# Keybindings.
map global user f ':fzf-mode<ret>' -docstring 'FZF'
map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP'
map global user r ':tmux-repl-vertical<ret>' -docstring 'REPL'
