# ~/.config/kak/kakrc

# This configuration for Kakoune uses Git submodules to pull inn all
# plugins, so as long as you do a recursive pull, most things should
# work by themselves. However, to get the LSP plugin working, you
# should install `cargo` (via e.g. `rustup`) and run `:plug-update`.
#
# External modules.
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "andreyorst/fzf.kak"
plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
}

# Settings.
set global ui_options ncurses_assistant=none
lsp-enable

# Use space as leader and backspace as deselection.
map global normal <space> , -docstring 'leader key'
map global normal <backspace> <space> -docstring 'remove other selections'
map global normal <a-backspace> <a-space> -docstring 'remove main selection'

# Populate the leader keymap.
map global user <ret> ':new<ret>' -docstring 'new'
map global user f ':fzf-mode<ret>' -docstring 'fzf'
map global user l ':enter-user-mode lsp<ret>' -docstring 'lsp'
