#+TITLE: Configuration for Doom Emacs
#+AUTHOR: Jabir Ali Ouassou
#+PROPERTY: header-args :tangle yes :cache yes :results silent

This is a *literate configuration file* for my [[https://github.com/hlissner/doom-emacs][Doom Emacs]] setup. This means
that it takes the form of an Org-mode document with inline code blocks, which
is *tangled* to an Emacs Lisp file =config.el= when I run =M-x doom/reload=.
The resulting code file represents my Doom Emacs configuration file.

* Table of contents :TOC:
- [[#metadata][Metadata]]
  - [[#target-platform][Target platform]]
  - [[#header-line][Header line]]
- [[#accounts-and-locations][Accounts and locations]]
  - [[#user-identity][User identity]]
  - [[#document-folders][Document folders]]
- [[#user-interface][User interface]]
- [[#keybindings][Keybindings]]
  - [[#macos-defaults][MacOS defaults]]
- [[#packages][Packages]]
  - [[#header-line-1][Header line]]
  - [[#better-defaults][Better defaults]]

* Metadata
** Target platform
The target platform is the [[https://bitbucket.org/mituharu/emacs-mac/src/master/]["Emacs Mac Port" by Mitsuharu Yamamoto]] running
on MacOS 11, which is available via [[https://github.com/railwaycat/homebrew-emacsmacport][Railwaycat's Homebrew repository]]. In
my experience, this provides the best Emacs experience on MacOS, e.g.
avoiding flickering/stuttering problems found in some other versions,
and supporting more of the expected MacOS default desktop behaviours.
Most of this config is however equally usable on Linux (which I used
when I first adopted Doom Emacs), and some may also work on Windows.

** Header line
This enables *lexical binding*, which is generally considered a good idea:
#+begin_src emacs-lisp
;;; -*- lexical-binding: t; -*-
#+end_src

To illustrate what this means, consider the following example from [[https://www.emacswiki.org/emacs/DynamicBindingVsLexicalBinding][EmacsWiki]]:
#+begin_src emacs-lisp :tangle no
    (let ((a 1))
      (let ((f (lambda () (print a))))
        (let ((a 2))
          (funcall f))))
#+end_src
Using *lexical binding* (enabled above), the code prints =1= since that is
what the variable =a= was at the time =f= was defined. Using *dynamic binding*
(the default), the above prints =2= since that is the most recent value of =a=.
Using lexical binding makes the code easier to debug and easier to optimize.

* Accounts and locations
This section defines the user accounts and system folders relevant for Emacs.
This includes mail accounts, mail folders, notes folders, and bibliographies.

** User identity
This is used by a lot in Emacs: mail, encryption, templates, snippets, etc.
#+begin_src emacs-lisp
(setq user-full-name "Jabir Ali Ouassou"
      user-mail-address "jabirali@switzerlandmail.ch")
#+end_src

** Document folders
These locations are especially used by Org-mode, for files and references.
#+begin_src emacs-lisp
(setq org-directory "~/iCloud/Org/"
      org-agenda-files '("~/iCloud/Org/")
      +org-capture-todo-file "~/iCloud/Org/Inbox.org")

(setq reftex-default-bibliography "~/Library/Zotero/Library.bib"
      bibtex-completion-bibliography '("~/Library/Zotero/Library.bib")
      org-ref-default-bibliography '("~/Library/Zotero/Library.bib"))
#+end_src

* User interface
Select the colortheme theme and fonts. For now, I'm using Doom One with default
MacOS fonts, but Gruvbox and Moonlight are also nice, and for programming the
Input and Iosevka fonts are cool. Note the difference between =doom-font= and
=doom-variable-pitch-font=: the former is monospace, the latter is "normal".
#+begin_src emacs-lisp
(setq doom-theme 'doom-one
      doom-font "Monaco-13"
      doom-variable-pitch-font "Monaco-13")
#+end_src

By default, I want an undecorated maximized frame for Emacs. This lets me use
Emacs on its own desktop (which I jump to via the keybinding =C-1= on MacOS),
and gives me enough space on a MacBook Air to have two 80-column files open.
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen  . maximized))
(add-to-list 'default-frame-alist '(undecorated . t))
#+end_src

Select the line number settings. This can be =nil= to turn them off, =t= to turn
on absolute line numbers, or ='relative= to turn on relative line numbers. While
I like the idea of relative numbers for easier Vim motion (jumps like e.g. =13k=),
these are not that useful when using folding in Doom Emacs; the numbers show
absolute line number differences while =#j= and =#k= use visual differences.
#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src
Note that line numbers in general can cause issues with smooth scrolling, and
look strange in buffers with wrapped lines, so disable in case of these issues.

* Keybindings
** MacOS defaults
These keybindings mirror what are used in other MacOS apps, e.g. iTerm2.
Here, the modifier =s= refers to the command key (⌘). Note that some
relevant keybindings, like ⌘s, ⌘t, ⌘w, and ⌘1-⌘9, are already defined.
#+begin_src emacs-lisp
(map!
 "s-[" 'evil-window-prev
 "s-]" 'evil-window-next
 "s-d" 'evil-window-vsplit
 "s-D" 'evil-window-split)
#+end_src

* Packages
This is a separate list of packages to enable or disable, which is tangled to a
separate Doom configuration file =packages.el=. See the =package!= macro for
more information about how to enable things, with the keywords =:recipe= for
stuff like GitHub packages and =:disable= to turn off built-in packages.

Remember to run =doom refresh= after updating this section!

** Header line
Disable byte-compilation of the package file.
#+begin_src elisp :tangle packages.el
;;; -*- no-byte-compile: t; -*-
#+end_src

** Better defaults
Disable the =hl-line= package. While it can look nice, it turns out simply being
distracting in modes like e.g. Org-mode, since (1) indentation is not highlighted
and (2) line-wrapping makes the size of the highlights inconsistent as you scroll.
#+begin_src elisp :tangle packages.el
(package! hl-line :disable t)
#+end_src
