# Package list for the HomeBrew and LinuxBrew systems.
# Activate this file using the command `brew bundle`.

# ------------------------------------------------------------ 
# Command-line applications
# ------------------------------------------------------------ 

# UNIX IDE.
brew "direnv"
brew "entr"
brew "fish"
brew "fzf"
brew "neovim"
brew "nnn"
brew "tmux"

# Documents.
brew "csvkit"
brew "graphviz"
brew "latexdiff"
brew "pandoc"
brew "pandoc-citeproc"
brew "pandoc-crossref"
cask "mactex-no-gui"

# Programming.
brew "black"
brew "cloc"
brew "gcc"
brew "git"
brew "gh"
brew "make"
brew "poetry"
brew "python"
brew "tcl-tk"

# Miscellaneous.
brew "atool"
brew "bat"
brew "dos2unix"
brew "exa"
brew "fd"
brew "htop"
brew "lzip"
brew "mas"
brew "moreutils"
brew "ripgrep"
brew "unix2dos"
brew "wget"



# ------------------------------------------------------------ 
# Graphical applications
# ------------------------------------------------------------ 

# User interface.
cask "alfred"
cask "bartender"
cask "command-tab-plus"
cask "amethyst"
mas "magnet", id: 441258766
mas "vimari", id: 1480933944

# Communication.
cask "discord"
cask "signal"
cask "zoomus"

# Entertainment.
cask "airflow"
cask "iina"
cask "spotify"
cask "steam"
cask "transmission"
mas "news-explorer", id: 1032670789

# Productivity.
cask "dash"
cask "iterm2"
cask "macvim"
cask "zotero"
mas "noteplan", id: 1137020764

# Privacy.
cask "expressvpn"
cask "little-snitch"
cask "micro-snitch"
mas "1password", id: 1333542190
mas "discovery", id: 1381004916
mas "wipr", id: 1320666476

# Apple.
mas "imovie", id: 408981434
mas "keynote", id: 409183694
mas "numbers", id: 409203825
mas "pages", id: 409201541

# Backup.
cask "arq"
cask "resilio-sync"
