# Package list for the HomeBrew and LinuxBrew systems.
# Activate this file using the command `brew bundle`.

# Better UNIX IDE.
brew "tmux"
brew "fish"
brew "neovim"
brew "direnv"
brew "entr"
brew "fzf"
brew "nnn"

# Standard commands.
brew "moreutils"
brew "ripgrep"
brew "atool"
brew "lzip"
brew "bat"
brew "exa"
brew "fd"

# Python packages.
brew "python"
brew "tcl-tk"
brew "poetry"
brew "black"

# Graphical apps.
cask "vlc"
cask "spotify"

# Mac App Store.
mas "Bear", id: 1091189122
mas "Master Password", id: 662763204
