;;; comint-mime-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from comint-mime.el

(autoload 'comint-mime-setup "comint-mime" "\
Enable rendering of MIME types in this comint buffer.

This function can be called in the hook of major modes deriving
from `comint-mode', or interactively after starting the comint." t)
(register-definition-prefixes "comint-mime" '("comint-mime-"))

;;; End of scraped data

(provide 'comint-mime-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; comint-mime-autoloads.el ends here
