;;; xenops-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xenops.el

(autoload 'xenops-mode "xenops" "\
A LaTeX editing environment.

\\{xenops-mode-map}

This is a minor mode.  If called interactively, toggle the `Xenops mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `xenops-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "xenops" '("xenops-"))


;;; Generated autoloads from xenops-aio.el

(register-definition-prefixes "xenops-aio" '("xenops-aio-"))


;;; Generated autoloads from xenops-apply.el

(register-definition-prefixes "xenops-apply" '("xenops-apply-"))


;;; Generated autoloads from xenops-auctex.el

(register-definition-prefixes "xenops-auctex" '("xenops-auctex-"))


;;; Generated autoloads from xenops-avy.el

(register-definition-prefixes "xenops-avy" '("xenops-"))


;;; Generated autoloads from xenops-doctor.el

(register-definition-prefixes "xenops-doctor" '("xenops-doctor"))


;;; Generated autoloads from xenops-element.el

(register-definition-prefixes "xenops-element" '("xenops-element-"))


;;; Generated autoloads from xenops-elements.el

(register-definition-prefixes "xenops-elements" '("xenops-elements-"))


;;; Generated autoloads from xenops-font.el

(register-definition-prefixes "xenops-font" '("xenops-"))


;;; Generated autoloads from xenops-footnote.el

(register-definition-prefixes "xenops-footnote" '("xenops-footnote-"))


;;; Generated autoloads from xenops-image.el

(register-definition-prefixes "xenops-image" '("xenops-image-"))


;;; Generated autoloads from xenops-math.el

(register-definition-prefixes "xenops-math" '("xenops-math-"))


;;; Generated autoloads from xenops-math-latex.el

(register-definition-prefixes "xenops-math-latex" '("xenops-"))


;;; Generated autoloads from xenops-minted.el

(register-definition-prefixes "xenops-minted" '("xenops-minted-"))


;;; Generated autoloads from xenops-overlay.el

(register-definition-prefixes "xenops-overlay" '("xenops-overlay-"))


;;; Generated autoloads from xenops-parse.el

(register-definition-prefixes "xenops-parse" '("xenops-parse-"))


;;; Generated autoloads from xenops-png.el

(register-definition-prefixes "xenops-png" '("xenops-png-"))


;;; Generated autoloads from xenops-src.el

(register-definition-prefixes "xenops-src" '("xenops-src-"))


;;; Generated autoloads from xenops-style.el

(register-definition-prefixes "xenops-style" '("xenops-style-"))


;;; Generated autoloads from xenops-util.el

(register-definition-prefixes "xenops-util" '("xenops-util-"))


;;; Generated autoloads from xenops-xen.el

(register-definition-prefixes "xenops-xen" '("xenops-"))

;;; End of scraped data

(provide 'xenops-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xenops-autoloads.el ends here
