export EDITOR=vim
export PROMPT_COMMAND="echo"
# export PS1='$ '
export PS1='\[\e[0;31m\]\h \[\e[0;34m\]\w \[\e[0;90m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2)\n\[\e[0m\]❯ \[\e[0m\]'

if [ -f ~/.bashrc.local ]; then 
     source ~/.bashrc.local
fi

clear
# if [ "$(command -v fish)" ]; then 
# 	exec fish
# fi
