# ~/.zshrc
#
# This is my personal Zsh config file, which uses the `zsh4humans` system
# to get (i) Fish-like sensible defaults and (ii) an ssh-portable config.

# Prepare framework.
zstyle ':z4h:' auto-update 'yes'
zstyle ':z4h:' auto-update-days '28'
zstyle ':z4h:' prompt-at-bottom 'yes'
zstyle ':z4h:bindkey' keyboard 'mac'
zstyle ':z4h:autosuggestions' forward-char 'accept'
zstyle ':z4h:fzf-complete' recurse-dirs 'yes'
zstyle ':z4h:direnv' enable 'yes'
zstyle ':z4h:direnv:success' notify 'no'
zstyle ':z4h:ssh:*.tmate.io' enable 'no'
zstyle ':z4h:ssh:*' enable 'yes'
zstyle ':z4h:ssh:*' send-extra-files '~/.vimrc'

# Prepare plugins.
# z4h install author/repo || return

# Initialize framework.
z4h init || return

# Define environment.
path=(~/.local/bin $path)

export CDPATH="~/Code:~/.config"
export EDITOR="subl -nw"
export GPG_TTY=$TTY

export ZSH_HIGHLIGHT_STYLES[path]=none
export ZSH_HIGHLIGHT_STYLES[path_prefix]=none

# Initialize plugins.
# z4h source author/repo/plugin.zsh

# Define keybindings.
z4h bindkey z4h-cd-back    Shift+Left
z4h bindkey z4h-cd-forward Shift+Right
z4h bindkey z4h-cd-up      Shift+Up
z4h bindkey z4h-cd-down    Shift+Down

# Directory aliases.
hash -d a=~/Archive
hash -d b=~/Boo
hash -d c=~/Code
hash -d d=~/Downloads
hash -d i=~/iCloud
hash -d n=~/Notes
hash -d z=~/.config


# Command aliases.
alias b="brew"
alias bb="brew sync"
alias bs="brew search"
alias bi="brew install"
alias be="e ~/.config/Brewfile"

alias e="subl -n"
alias ee="e ~/.subl"

alias g="git"
alias ga="git add"
alias gc="git commit"
# function gc { [[ -z "$@" ]] && git commit || git commit -m }
alias gd="git diff"
alias gl="git log"
alias gp="git pull"
alias gs="git status"

alias o="open"
alias or="open -R"

alias zz="exec zsh"
alias zu="z4h update"
alias ze="subl -nw ~/.p10k.zsh ~/.zshrc && exec zsh"
alias zp="p10k configure"

alias l="ls"
alias ll="ls -l"
alias la="ls -la"

# Set shell options.
setopt glob_dots
setopt no_auto_menu

# Source externals.
if [ "$(command -v zoxide)" ]; then
	eval "$(zoxide init --cmd cd zsh)"
fi

# Hook: automatic ls.
_ls_on_cwd_change() {
  command ls;
}
add-zsh-hook chpwd _ls_on_cwd_change

export TERM=xterm-kitty
