# ~/.bash_profile: Minimal configuration for remote use.

# Load the interactive configuration.
if [ -f "$HOME/.bashrc" ]; then
	source ~/.bashrc
fi

# Change shell without `chsh` rights.
if [ -x "$(command -v zsh)" ]; then
	exec zsh -l
fi
