# ~/.bash_profile: Minimal configuration for remote use.

# Default configuration.
if [ -f "$HOME/.bashrc" ]; then
	source ~/.bashrc
fi

# Change shell if possible.
if [ -x "$(command -v fish)" ]; then
	exec fish -l
fi
